/*
Toda la configuración del juego está aquí, no hay nada hardcoded
*/
DEBUG = false;

//ENGINE
CANVAS_MARGIN_VERTICAL = 200;
CANVAS_MARGIN_HORIZONTAL = 20;
FPS = 120;
TIME_DELTA = 1000 / FPS;
SCREEN_WIDTH = 336;
SCREEN_HEIGHT = 372;
BACKGROUND_COLOR = "rgba(0,0,0,1)";
TILE_SIZE = 12;
SPRITE_SIZE = 24;
COLLISION_SIZE = 15;
NCOLS = SCREEN_WIDTH / TILE_SIZE;
NROWS = SCREEN_HEIGHT / TILE_SIZE;
PATH_COLOR_R = 0;
PATH_COLOR_G = 252;
PATH_COLOR_B = 30;


//JUGABILIDAD
BALL_1_SCORE = 10;
BALL_2_SCORE = 50;
CHERRY_SCORE = 100;
STRAWBERRY_SCORE = 300;
ORANGE_SCORE = 500;
APPLE_SCORE = 700;
GRAPES_SCORE = 1000;
GALAXIAN_SCORE = 2000;
BELL_SCORE = 3000;
KEY_SCORE = 5000;
FRIGHTENED_DURATION = 10; //en segundos
EXTRA_LIFE_SCORE = 10000;

//CONTROLES
SWIPE_THRESHOLD = 80;
SWIPE_RESTRAINT = 50;
SWIPE_ALLOWEDTIME = 300; //ms

//POSICIONES PARA DISPERSIÓN
BLINKY_SCATTER_MODE_TARGET = [0,23];
INKY_SCATTER_MODE_TARGET = [30,27];
PINKY_SCATTER_MODE_TARGET = [0,4];
CLYDE_SCATTER_MODE_TARGET = [30,0];

//POSICIONES INICIALES
PACMAN_INIT_POS = [156, 270];
BLINKY_INIT_POS = [156, 126];
INKY_INIT_POS = [132, 167];
PINKY_INIT_POS = [156, 159];
CLYDE_INIT_POS = [180, 163];

POS_CONSIDERED_OUT_HOME = [156,126];
POS_CONSIDERED_IN_HOME = [156,157];

HOME_ENTRANCE_TILE= [11,13];



//SONIDOS
SOUND_EAT_BALL = "assets/sounds/eat_ball.mp3";
SOUND_EAT_FRUIT = "assets/sounds/eat_fruit.mp3";
SOUND_EAT_GHOST = "assets/sounds/eat_ghost.mp3";
SOUND_FRIGHTENED = "assets/sounds/frightened.mp3";
SOUND_MUSIC = "assets/sounds/music.mp3";
SOUND_RETURNING = "assets/sounds/returning.mp3";



//SPRITES
ASSETS_SPRITES = "assets/spritemap.png";
ASSETS_PATH = "assets/path.png";
ASSETS_CHECKERBOARD = "assets/checkerboard.png";
ASSETS_READY = "assets/ready.png";
ASSETS_GAMEOVER = "assets/game_over.png";
READY_WIDTH = 47;
READY_HEIGHT = 7;
READY_X = 145;
READY_Y = 206;
GAMEOVER_WIDTH = 79;
GAMEOVER_HEIGHT =  7;
GAMEOVER_X = 128;
GAMEOVER_Y = 206;