/*
Toda la configuración del juego está aquí, no hay nada hardcoded
*/

//engine
CANVAS_MARGIN_TOP = 100;
FPS = 60;
TIME_DELTA = 1000 / FPS;
SCREEN_WIDTH = 336;
SCREEN_HEIGHT = 372;
BACKGROUND_COLOR = "rgba(0,0,0,1)";
TILE_SIZE = 12;
NCOLS = SCREEN_WIDTH / TILE_SIZE;
NROWS = SCREEN_HEIGHT / TILE_SIZE;

ASSETS_SPRITES = "assets/spritemap.png";
ASSETS_PATH = "assets/path.png";
PATH_COLOR_R = 0;
PATH_COLOR_G = 252;
PATH_COLOR_B = 30;


BALL_1_SCORE = 10;
BALL_2_SCORE = 50;


BLINKY_SCATTER_MODE_TARGET = [0,23];
INKY_SCATTER_MODE_TARGET = [30,27];
PINKY_SCATTER_MODE_TARGET = [0,4];
CLYDE_SCATTER_MODE_TARGET = [30,0];