/*
Toda la configuración del juego está aquí, no hay nada hardcoded
*/
DEBUG = false;
//engine
CANVAS_MARGIN_VERTICAL = 200;
CANVAS_MARGIN_HORIZONTAL = 20;
FPS = 60;
TIME_DELTA = 1000 / FPS;
SCREEN_WIDTH = 336;
SCREEN_HEIGHT = 372;
BACKGROUND_COLOR = "rgba(0,0,0,1)";
TILE_SIZE = 12;
NCOLS = SCREEN_WIDTH / TILE_SIZE;
NROWS = SCREEN_HEIGHT / TILE_SIZE;

ASSETS_SPRITES = "assets/spritemap.png";
ASSETS_PATH = "assets/path.png";
ASSETS_CHECKERBOARD = "assets/checkerboard.png";
ASSETS_READY = "assets/ready.png";
ASSETS_GAMEOVER = "assets/game_over.png";
READY_WIDTH = 47;
READY_HEIGHT = 7;
READY_X = 145;
READY_Y = 206;
GAMEOVER_WIDTH = 79;
GAMEOVER_HEIGHT =  7;
GAMEOVER_X = 128;
GAMEOVER_Y = 206;


PATH_COLOR_R = 0;
PATH_COLOR_G = 252;
PATH_COLOR_B = 30;


BALL_1_SCORE = 10;
BALL_2_SCORE = 50;


BLINKY_SCATTER_MODE_TARGET = [0,23];
INKY_SCATTER_MODE_TARGET = [30,27];
PINKY_SCATTER_MODE_TARGET = [0,4];
CLYDE_SCATTER_MODE_TARGET = [30,0];


PACMAN_INIT_POS = [156, 270];

BLINKY_INIT_POS = [156, 126];


INKY_INIT_POS = [132, 167];


PINKY_INIT_POS = [156, 159];


CLYDE_INIT_POS = [180, 163];



POS_CONSIDERED_OUT_HOME = [156,126];
POS_CONSIDERED_IN_HOME = [156,157];

HOME_ENTRANCE_TILE= [11,13];